/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

// PWM
#include "GTM_TOM_PWM.h"
#include "Bsp.h"

// timer related
#include "IfxStm.h"
#include "IfxCpu_Irq.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

// scheduler related
#include "Driver_Stm.h"
#include "Driver_Adc.h"

// LED
#define PCn_2_IDX 19
#define P2_IDX 2

//SW 3
#define PCn_0_IDX 3
#define PCn_1_IDX 11
#define P1_IDX 1

// ERU related
#define EXIS0_IDX 4
#define FEN0_IDX 8
#define EIEN0_IDX 11
#define INP0_IDX 12
#define IGP0_IDX 14

// SRC related
#define SRE_IDX 10
#define TOS_IDX 11


typedef struct
{
    uint32_t u32nuCnt1ms;
    uint32_t u32nuCnt10ms;
    uint32_t u32nuCnt100ms;
    uint32_t u32nuCnt1000ms;

}TestCnt;

// Task scheduling related
void AppTask10ms(void);
void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

/***********************************************************************/
/*Variable*/
/***********************************************************************/
#define WAIT_TIME   1000              /* Number of milliseconds to wait between each duty cycle change                */
TestCnt stTestCnt;
uint32_t adcResult = 0;
IfxCpu_syncEvent cpuSyncEvent = 0;


void initGPIO(void);

//int twinkleMelody[] = {
//        0, 14, 0, 14,  7, 14, 7, 14,  9, 14, 9, 14, 7, 14,  5, 14, 5, 14,  4, 14, 4, 14,  2, 14, 2, 14, 0, 14,
//        7, 14, 7, 14,  5, 14, 5, 14,  4, 14, 4, 14, 2, 14,  7, 14, 7, 14,  5, 14, 5, 14,  4, 14, 4, 14, 2, 14,
//        0, 14, 0, 14,  7, 14, 7, 14,  9, 14, 9, 14, 7, 14,  5, 14, 5, 14,  4, 14, 4, 14,  2, 14, 2, 14, 0, 14
//};
//
//int twinkleDurations[] = {
//        500, 5, 500, 5,  500, 5, 500, 5,  500, 5, 500, 5, 1000, 5,  500, 5, 500, 5,  500, 5, 500, 5,  500, 5, 500, 5, 1000, 5,
//        500, 5, 500, 5,  500, 5, 500, 5,  500, 5, 500, 5, 1000, 5,  500, 5, 500, 5,  500, 5, 500, 5,  500, 5, 500, 5, 1000, 5,
//        500, 5, 500, 5,  500, 5, 500, 5,  500, 5, 500, 5, 1000, 5,  500, 5, 500, 5,  500, 5, 500, 5,  500, 5, 500, 5, 1000, 5,
//};
//int length = sizeof(twinkleMelody) / sizeof(twinkleDurations[0]);

int tempMelody[] = {
    7, 24, 7, 24, 9, 24, 7, 24, 12, 24, 11, 24,
    7, 24, 7, 24, 9, 24, 7, 24, 14, 24, 12, 24,
    7, 24, 7, 24, 12, 24, 16, 24, 11, 24, 9, 24,
    17, 24, 17, 24, 16, 24, 12, 24, 14, 24, 12, 24
};

int tempDuration[] = {
    400, 5, 400, 5, 800, 5, 800, 5, 800, 5, 1600, 5,
    400, 5, 400, 5, 800, 5, 800, 5, 800, 5, 1600, 5,
    400, 5, 400, 5, 800, 5, 800, 5, 800, 5, 1600, 5,
    400, 5, 400, 5, 800, 5, 800, 5, 800, 5, 1600, 5
};
int length = sizeof(tempMelody) / sizeof(tempDuration[0]);

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    Ifx_TickTime ticksFor1000ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

    initGPIO();
    Driver_Stm_Init();
    Driver_Adc_Init();
    initGtmTomPwm();

    while(1)
    {
        for(int i=0; i<length; i++){
            makeSound(tempMelody[i]);
            Ifx_TickTime ticksFor1000ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, tempDuration[i]);
            waitTime(ticksFor1000ms);
        }
    }
}

void initGPIO(void){
    //SWITCH
    P02_IOCR0.U &= ~(0x1F << PCn_0_IDX | 0x1F << PCn_1_IDX);
    P02_IOCR0.U |= (0x02 << PCn_0_IDX | 0x02 << PCn_1_IDX);

    // BLUE & RED LED
    IfxPort_setPinModeOutput(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

//    // 실습 1번
//    //D9 P2.7 RED
//    IfxPort_setPinModeOutput(IfxPort_P02_7.port, IfxPort_P02_7.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
//
//    //D10 P10.5 GREEN
//    IfxPort_setPinModeOutput(IfxPort_P10_5.port, IfxPort_P10_5.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
//
//    //D11 P10.3 BLUE
//    IfxPort_setPinModeOutput(IfxPort_P10_3.port, IfxPort_P10_3.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    // 실습 2번
    //A1 P32.4 photo cell
//    IfxPort_setPinModeInput(IfxPort_P32_4.port, IfxPort_P32_4.pinIndex, IfxPort_InputMode_noPullDevice);
}

void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;
}

//void AppTask10ms(void)
//{
//    stTestCnt.u32nuCnt10ms++;
//}

void AppTask10ms(void) {
    stTestCnt.u32nuCnt10ms++;
    /*ADC Test*/
    adcResult = Driver_Adc0_DataObtain();
    fadeLED(adcResult);
    Driver_Adc0_ConvStart();
}

void AppTask100ms(void)
{
    // 실습 1번
//    static int flag = 0;
//    if(flag == 0)
//    {
//        IfxPort_setPinLow(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex);
//        flag = 1;
//    }
//    else
//    {
//        IfxPort_setPinHigh(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex);
//        flag = 0;
//    }
    stTestCnt.u32nuCnt100ms++;
}

void AppTask1000ms(void)
{
//    static int flag = 0;
//    if(flag == 0)
//    {
//        IfxPort_setPinLow(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
//        flag = 1;
//    }
//    else
//    {
//        IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
//        flag = 0;
//    }
    stTestCnt.u32nuCnt1000ms++;

}

void AppScheduling(void)
{
    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }
        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}
